### ISSUE TITLE
Add mini login form to navbar

### ISSUE THREAD

**Issue by SgtCoDFish** [UoLCompSoc/web2015#7]
It'd be nice to have a login bar integrated into the navigation bar for desktop users. It needs to follow a similar kind of style to the login form in site/application/views/login.php, but fit into the navigation bar at the top.

We need E-Mail, Password, Submit and a register link if on desktop. Note that the form needs codeigniter specific PHP as there is in login.php; all that really needs changing is the layout of the form so it fits inline nicely.

If on mobile, the user should just have a menu item linking to the login page as is currently there.

**Comment by praveenscience** [comment]
:+1:

**Comment by SgtCoDFish** [comment]
Closing as wontfix, I think it's fine how it is for now. This is a stretch goal at best.
